name: 'powerload'
version: '3.9'
services:
  nginx:
    container_name: powerload_nginx
    build:
        context: .
        dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      # {hostPath}:{imagePath} volumes provide us the way to share data between host and container
    volumes:
      - ../:/var/www/html
    networks:
      - powerload_network
    depends_on:
      - db
      - backend
      - frontend
  db:
    container_name: 'powerload_db'
    build:
      context: .
      dockerfile: mysql.dockerfile
    ports:
      - 3306:3306
    networks:
      - powerload_network
  frontend:
    container_name: 'powerload_frontend'
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ../frontend:/var/www
    networks:
      - powerload_network
    depends_on:
      - db
      - backend
  backend:
    container_name: 'powerload_backend'
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ../backend:/var/www
    networks:
      - powerload_network
    depends_on:
      - db
  composer:
    container_name: 'powerload_composer'
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ../backend/:/var/www
    networks:
      - powerload_network
  artisan:
    container_name: 'powerload_artisan'
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    volumes:
      - ../backend:/var/www
    working_dir: /var/www
    depends_on:
      - db
    entrypoint: [ 'php', '/var/www/artisan' ]
    networks:
      - powerload_network
  npm:
    container_name: 'powerload_npm'
    build:
      context: .
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend:/var/www
    working_dir: /var/www
    entrypoint: [ 'npm', 'run', 'dev']
    networks:
      - powerload_network
networks:
  powerload_network:
    driver: bridge